#!/bin/sh -e

# Build autoconf 2.13 for browser's sole use.
(
    cd autoconf2.13

    ./configure \
        --prefix="$PWD/../junk" \
        --program-suffix=-2.13

    make
    make install
)

# Build yasm for browser's sole use.
(
    cd yasm

    ./configure \
        --prefix="$PWD/../junk"

    make
    make install
)
export PATH="$PWD/junk/bin:$PATH"

sed 's#%SRCDIR%#'"$(realpath .)"'#g' mozconfig.in > .mozconfig

for patch in *.patch; do
    patch -p1 < "$patch"
done

export LDFLAGS="$LDFLAGS -Wl,-rpath=/usr/lib/browser"

./mach build
./mach package

mkdir -p "$1/usr/bin"
mkdir -p "$1/usr/lib"

cp -r objdir/dist/palemoon "$1/usr/lib/browser"
ln -s ../lib/browser/palemoon "$1/usr/bin/browser"
