#!/bin/sh -e

# Use relative date format '3s', '3d', etc instead of '3 seconds ago', '3 days ago', etc.
sed -i 's|Q_("%"PRItime" second ago", "%"PRItime" seconds ago", diff)|"%"PRItime"s"|g' date.c
sed -i 's|Q_("%"PRItime" minute ago", "%"PRItime" minutes ago", diff)|"%"PRItime"m"|g' date.c
sed -i 's|Q_("%"PRItime" hour ago", "%"PRItime" hours ago", diff)|"%"PRItime"h"|g' date.c
sed -i 's|Q_("%"PRItime" day ago", "%"PRItime" days ago", diff)|"%"PRItime"d"|g' date.c
sed -i 's|Q_("%"PRItime" week ago", "%"PRItime" weeks ago", (diff + 3) / 7)|"%"PRItime"w"|g' date.c
sed -i 's|Q_("%"PRItime" month ago", "%"PRItime" months ago", (diff + 15) / 30)|"%"PRItime"M"|g' date.c
sed -i 's|Q_("%"PRItime" year", "%"PRItime" years", years)|"%"PRItime"y"|g' date.c
sed -i 's|Q_("%s, %"PRItime" month ago", "%s, %"PRItime" months ago", months)|"%s, %"PRItime"M"|g' date.c
sed -i 's|Q_("%"PRItime" year ago", "%"PRItime" years ago", years)|"%"PRItime"y"|g' date.c
sed -i 's|Q_("%"PRItime" year ago", "%"PRItime" years ago", (diff + 183) / 365)|"%"PRItime"y"|g' date.c

export CFLAGS="$CFLAGS -static"

cat > config.mak <<EOF
NO_GETTEXT=YesPlease
NO_SVN_TESTS=YesPlease
NO_TCLTK=YesPlease
NO_EXPAT=YesPlease
NO_NSEC=YesPlease
NO_PYTHON=YesPlease
NO_PERL=YesPlease
NO_SVN_TESTS=YesPlease
NO_SYS_POLL_H=1
NO_CROSS_DIRECTORY_HARDLINKS=1
NO_INSTALL_HARDLINKS=1
EOF

./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    ac_cv_lib_curl_curl_global_init=yes \
    ac_cv_snprintf_returns_bogus=no \
    ac_cv_fread_reads_directories=yes

make LIBS="$(curl-config --static-libs) libgit.a xdiff/lib.a -lz"
make DESTDIR="$1" install

cp -Rf man "$1/usr/share/man"
