#!/bin/sh -e

# Disable assertions
sed -i "/config.set('BUILDER_DESCRIPTION', 1)/a config.set('NDEBUG', 1)" meson.build

export DESTDIR="$1"
export LDFLAGS="$LDFLAGS -Wl,-z,lazy"

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Ddefault-dri=3 \
    -Dxvmc=false \
    -Dvalgrind=false \
    . build

ninja -C build
ninja -C build install
