#!/bin/sh -e

# Disable assertions which sometimes causes crashes
sed -i 's/#ifndef NDEBUG/#if 0/g' src/sna/kgem.c

export DESTDIR="$1"
export LDFLAGS="$LDFLAGS -Wl,-z,lazy"

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Ddefault-dri=3 \
    -Dxvmc=false \
    -Dvalgrind=false \
    . build

ninja -C build
ninja -C build install
