#!/bin/sh -e

install -Dm644 DroidSans.ttf             "$1/usr/share/fonts/droid/DroidSans.ttf"
install -Dm644 DroidSans-Bold.ttf        "$1/usr/share/fonts/droid/DroidSans-Bold.ttf"
install -Dm644 DroidSansMono.ttf         "$1/usr/share/fonts/droid/DroidSansMono.ttf"
